apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jarvis-sma-planner.fullname" . }}
  labels:
    {{- include "jarvis-sma-planner.labels" . | nindent 4 }}
data:
  modbus-host-ip: {{ .Values.config.modbusHostIP | quote }}
  modbus-host-port: {{ .Values.config.modbusHostPort | quote }}
  modbus-unit-id: {{ .Values.config.modbusUnitID | quote }}
