{{- if .Values.rbac.enable -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "jarvis-sma-planner.fullname" . }}
  labels:
    {{- include "jarvis-sma-planner.labels" . | nindent 4 }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - configmaps
  verbs:
  - get
  - list
  - update
  - watch
{{- end -}}